name: 🚀 Feature Request
description: File a Feature Request
title: "[FEATURE REQUEST] <title>"
labels: [enhancement]
body:
  - type: dropdown
    id: level
    attributes:
      label: Area of the resources that should be enhanced?
      options:
        - DDD & Event Storming 101 - Let's get things started
        - DDD & Event Storming 201 - Give me more
        - DDD & Event Storming 301 and beyond - Going all in
        - Courses
        - DDD and Legacy
        - DDD Community
        - Further DDD Goodies
    validations:
      required: true
  - type: input
    attributes:
      label: Link to resource
      description: Put here the link to the resource you would like to see as part of the repository.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description
      description: Describe why you think that this resource provides additional value for a DDD learner.
    validations:
      required: true
